### ISSUE TITLE
Switch to sensor instead of Binary

### ISSUE THREAD

**Issue by rbflurry** [Limych/HomeAssistantComponents#2]
Could you show me where or how to change the output of this component to be a sensor rather then a binary sensor.

My thought is to change the sensor state to say yes/no or true/false so that it is easy to understand for anyone looking at the state.

**Comment by Limych** [comment]
There are many components.
What exactly is it about?

**Comment by rbflurry** [comment]
Sorry. The Car wash sensor. I would like to be able to change it to a question.

Is it safe to wash the car?    (Yes/No)

**Comment by Limych** [comment]
You can use template sensor for that:

```yaml
sensor:
  - platform: template
    sensors:
      car_wash_yes_no:
        value_template: >-
          {% if is_state('binary_sensor.car_wash', 'on') %}
            yes
          {% else %}
            no
          {% endif %}
```

https://www.home-assistant.io/components/template/
